"""Constants for the EntangledHome integration."""

DOMAIN = "entangledhome"
TITLE = "EntangledHome"
DEFAULT_CATALOG_SYNC = True
DEFAULT_CONFIDENCE_GATE = False
DEFAULT_REFRESH_INTERVAL_MINUTES = 5
DEFAULT_PLEX_SYNC = True
DEFAULT_CONFIDENCE_THRESHOLD = 0.7
DEFAULT_NIGHT_MODE_ENABLED = False
DEFAULT_NIGHT_MODE_START_HOUR = 23
DEFAULT_NIGHT_MODE_END_HOUR = 6
DEFAULT_DEDUPLICATION_WINDOW = 2.0

CONF_ADAPTER_URL = "adapter_url"
CONF_QDRANT_HOST = "qdrant_host"
CONF_QDRANT_API_KEY = "qdrant_api_key"
OPT_ENABLE_CATALOG_SYNC = "enable_catalog_sync"
OPT_ENABLE_CONFIDENCE_GATE = "enable_confidence_gate"
OPT_REFRESH_INTERVAL_MINUTES = "refresh_interval_minutes"
OPT_ENABLE_PLEX_SYNC = "enable_plex_sync"
OPT_CONFIDENCE_THRESHOLD = "confidence_threshold"
OPT_NIGHT_MODE_ENABLED = "night_mode_enabled"
OPT_NIGHT_MODE_START_HOUR = "night_mode_start_hour"
OPT_NIGHT_MODE_END_HOUR = "night_mode_end_hour"
OPT_DEDUPLICATION_WINDOW = "deduplication_window_seconds"
OPT_ADAPTER_SHARED_SECRET = "adapter_shared_secret"

DEFAULT_OPTION_VALUES = (
    (OPT_ENABLE_CATALOG_SYNC, DEFAULT_CATALOG_SYNC),
    (OPT_ENABLE_CONFIDENCE_GATE, DEFAULT_CONFIDENCE_GATE),
    (OPT_REFRESH_INTERVAL_MINUTES, DEFAULT_REFRESH_INTERVAL_MINUTES),
    (OPT_ENABLE_PLEX_SYNC, DEFAULT_PLEX_SYNC),
    (OPT_CONFIDENCE_THRESHOLD, DEFAULT_CONFIDENCE_THRESHOLD),
    (OPT_NIGHT_MODE_ENABLED, DEFAULT_NIGHT_MODE_ENABLED),
    (OPT_NIGHT_MODE_START_HOUR, DEFAULT_NIGHT_MODE_START_HOUR),
    (OPT_NIGHT_MODE_END_HOUR, DEFAULT_NIGHT_MODE_END_HOUR),
    (OPT_DEDUPLICATION_WINDOW, DEFAULT_DEDUPLICATION_WINDOW),
    (OPT_ADAPTER_SHARED_SECRET, ""),
)
