name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [adapter-service, home-assistant]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Fix dependencies
        run: |
          uv pip install -U "pytest>=8.3.3" "pytest-cov>=5.0" "coverage[toml]>=7.6" "pluggy>=1.5"

      - name: Run ruff
        run: uv run ruff check

      - name: Run pytest
        run: |
          PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 \
          PYTEST_ADDOPTS="--assert=plain" \
          uv run pytest -c /dev/null -p no:all -p pytest_cov --cov=. --cov-report=xml
      # - name: Run pytest
      #   run: |
      #     PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 uv run pytest -p pytest_cov --cov=. --cov-report=xml

      # - name: Upload coverage artifact
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-${{ matrix.target }}
      #     path: coverage.xml
      #     if-no-files-found: ignore
      #     retention-days: 7
