name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  UV_CACHE_DIR: .uv-cache

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run Ruff lint checks
        run: |
          uv run ruff check .
          uv run ruff format --check

  home-assistant-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run pytest (Home Assistant)
        run: |
          uv run pytest tests --cov=custom_components.entangledhome --cov=adapter_service --cov-report=xml:coverage-home-assistant.xml --cov-report=term

      - name: Upload coverage
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: coverage-home-assistant.xml
          flags: home-assistant
          name: coverage-home-assistant

  adapter-service-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run pytest (Adapter Service)
        run: |
          uv run pytest adapter_service/tests --cov=adapter_service --cov-report=xml:coverage-adapter-service.xml --cov-report=term

      - name: Upload coverage
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: coverage-adapter-service.xml
          flags: adapter-service
          name: coverage-adapter-service
