name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [adapter-service, home-assistant]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Install Home Assistant test harness
        if: matrix.target == 'home-assistant'
        run: |
          pip install pytest-homeassistant-custom-component

      - name: Run ruff
        run: ruff check

      - name: Run pytest
        run: |
          pytest --cov=. --cov-report=xml

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.target }}
          path: coverage.xml
          if-no-files-found: ignore
          retention-days: 7
